name: citybusters
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  graphql_flutter: ^5.1.0
  get: 4.6.1
  hive_flutter: ^1.1.0
  equatable: ^2.0.3
  firebase_auth: ^3.3.16
  hexcolor: ^2.0.7
  google_fonts: ^2.3.2
  nanoid: ^1.0.0
  shared_preferences: ^2.0.13
  cached_network_image: ^3.2.0
  meilisearch: ^0.3.1
  image_picker: ^0.8.5+1
  firebase_storage: ^10.2.15
  cloud_firestore: ^3.1.14
  custom_marker: ^1.0.0
  confetti: ^0.6.0

  # qr
  qr_code_scanner: ^0.7.0
  qr_flutter: ^4.0.0

  # map
  google_maps_flutter: ^2.0.6
  geolocator: ^7.0.3
  geocoding: ^2.0.4
  flutter_polyline_points: ^1.0.0

  firebase_core: ^1.15.0
  flutter_maps: ^0.1.0

  mobileapp_components:
   
    path: /Users/carolina/dev/vibin/app-packages/mobileapp-components
    #git:
    #  url: https://github.com/vibinorg/mobileapp-components.git

  mobileapp_utils:
   
    path: /Users/carolina/dev/vibin/app-packages/mobileapp-utils
    #git:
    #  url: https://github.com/vibinorg/mobileapp-utils.git

  mobileapp_icons_dep:
  
    path: /Users/carolina/dev/vibin/app-packages/mobileapp-icons-dep
    #git:
    #  url: https://github.com/vibinorg/mobileapp-icons-dep.git

  mobileapp_icons:
    #path: /Users/21gilles/dev/vibin/app-packages/mobileapp-icons
    path: /Users/carolina/dev/vibin/app-packages/mobileapp-icons

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/

