// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnDpkcn0dFjOau1vUVgplfGURb9fxEwLQ',
    appId: '1:578561061679:android:8bce7f32af475a7f6f67da',
    messagingSenderId: '578561061679',
    projectId: 'citybusters-50fd0',
    storageBucket: 'citybusters-50fd0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLrXNgR7jcJia3EpF0Mf76fWf3kHJ-NdQ',
    appId: '1:578561061679:ios:561e163ea202e9356f67da',
    messagingSenderId: '578561061679',
    projectId: 'citybusters-50fd0',
    storageBucket: 'citybusters-50fd0.appspot.com',
    iosClientId:
        '578561061679-u2m5638t52a5m2dhdnfk088t72f93l0f.apps.googleusercontent.com',
    iosBundleId: 'com.example.citybusters',
  );
}
